<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container37bx670\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container37bx670/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container37bx670.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container37bx670\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container37bx670\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '37bx670',
    'container.build_id' => 'bb762288',
    'container.build_time' => 1567628918,
], __DIR__.\DIRECTORY_SEPARATOR.'Container37bx670');
