<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUw1xkxa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUw1xkxa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUw1xkxa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUw1xkxa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUw1xkxa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Uw1xkxa',
    'container.build_id' => '52cd0b72',
    'container.build_time' => 1566683811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUw1xkxa');
